title: "一个入坑物联网开发的前端工程师"
description: "最近买了“大”玩具：树莓派4B,但是有点不知道怎么玩:_("
author:
  name: "HPanpan(盼儿哥)"
  email: "hanpanpan92@gmail.com"
  url: "https://blog.hanshuqiang.top"

baseurl: /

source: .
destination: ./_site
permalink: /:title
 
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom variables
owner : "HPanpan"
year : "2021"
